# Generated by Django 5.2.7 on 2025-10-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_illnesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='image_url',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
