# Generated by Django 5.2.7 on 2025-10-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_illnesses', '0002_alter_illness_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illness',
            name='image_url',
        ),
        migrations.AddField(
            model_name='illness',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
