# Generated by Django 5.2.7 on 2025-11-08 13:29

import app_illnesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_illnesses', '0003_remove_illness_image_url_illness_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=app_illnesses.models.illness_image_upload_to),
        ),
    ]
