# Generated by Django 6.0 on 2026-05-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_herbs', '0009_favorite'),
        ('app_illnesses', '0004_alter_illness_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illness',
            name='recommended_herbs',
        ),
        migrations.AddField(
            model_name='illness',
            name='recommended_herbs',
            field=models.ManyToManyField(blank=True, related_name='related_illnesses', to='app_herbs.herb'),
        ),
    ]
