# Generated by Django 6.0 on 2026-05-11 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pinreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELETED', 'Deleted'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
