# Generated by Django 6.0 on 2026-05-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0002_alter_pinreport_reported_by_alter_pinreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
    ]
