# Generated by Django 6.0 on 2026-05-11 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_herbs', '0009_favorite'),
        ('app_reports', '0003_alter_pinreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinreport',
            name='pin',
        ),
        migrations.AddField(
            model_name='pinreport',
            name='reported_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='app_herbs.herbpin'),
        ),
    ]
