# Generated by Django 6.0 on 2026-05-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0004_remove_pinreport_pin_pinreport_reported_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinreport',
            name='original_pin_owner',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
