# Generated by Django 5.2.7 on 2025-10-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_herbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image_url',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
