# Generated by Django 5.2.7 on 2025-10-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_herbs', '0002_alter_herb_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herb',
            old_name='image_url',
            new_name='image',
        ),
    ]
