# Generated by Django 5.2.7 on 2025-10-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_herbs', '0003_rename_image_url_herb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
