# Generated by Django 5.2.7 on 2025-11-08 12:14

import app_herbs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_herbs', '0004_alter_herb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=app_herbs.models.herb_image_upload_to),
        ),
    ]
