# Generated by Django 5.2.5 on 2025-12-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_herbs', '0006_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
