# Generated by Django 5.2.7 on 2025-12-28 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_herbs', '0007_herb_latitude_herb_longitude_delete_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='herb',
            name='longitude',
        ),
        migrations.CreateModel(
            name='HerbPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='app_herbs.herb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herb_pins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
